// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzzwFTiJPyJ3ACwGOzR7O4EAfF6U4ZQoU',
    appId: '1:682947339145:web:a9388553bdf351edcf3758',
    messagingSenderId: '682947339145',
    projectId: 'distribuidas-f7a12',
    authDomain: 'distribuidas-f7a12.firebaseapp.com',
    storageBucket: 'distribuidas-f7a12.firebasestorage.app',
    measurementId: 'G-KMV47KP65E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBykNzkkoD-EITE-xSUIeexr8rzbfOIu4k',
    appId: '1:682947339145:android:1ad776337375e497cf3758',
    messagingSenderId: '682947339145',
    projectId: 'distribuidas-f7a12',
    storageBucket: 'distribuidas-f7a12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrO_cqehEmg-0ApL3_UsInj3rbFw1uhQ',
    appId: '1:682947339145:ios:1c22d017c853bd46cf3758',
    messagingSenderId: '682947339145',
    projectId: 'distribuidas-f7a12',
    storageBucket: 'distribuidas-f7a12.firebasestorage.app',
    iosClientId: '682947339145-qc23s73k9hfkma3411cltvl8t757aair.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVrO_cqehEmg-0ApL3_UsInj3rbFw1uhQ',
    appId: '1:682947339145:ios:1c22d017c853bd46cf3758',
    messagingSenderId: '682947339145',
    projectId: 'distribuidas-f7a12',
    storageBucket: 'distribuidas-f7a12.firebasestorage.app',
    iosClientId: '682947339145-qc23s73k9hfkma3411cltvl8t757aair.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzzwFTiJPyJ3ACwGOzR7O4EAfF6U4ZQoU',
    appId: '1:682947339145:web:b3b5aa72acaf6190cf3758',
    messagingSenderId: '682947339145',
    projectId: 'distribuidas-f7a12',
    authDomain: 'distribuidas-f7a12.firebaseapp.com',
    storageBucket: 'distribuidas-f7a12.firebasestorage.app',
    measurementId: 'G-SHN9TLCMQY',
  );
}
