upstream wordpress_backend {
    server wordpress-1:80;
    server wordpress-2:80 backup; # Simula el IP virtual / Keepalived
}

upstream joomla_backend {
    server joomla-1:80;
    server joomla-2:80 backup;
}

server {
    listen 80;
    server_name localhost;

    # Redireccionar sin barra al final a con barra al final para evitar caer en el fallback
    location = /wordpress {
        return 301 $scheme://$http_host/wordpress/;
    }

    location = /joomla {
        return 301 $scheme://$http_host/joomla/;
    }

    # Rutas para WordPress
    location /wordpress/ {
        proxy_pass http://wordpress_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
        proxy_read_timeout 10s;
    }

    # Rutas para Joomla
    location /joomla/ {
        proxy_pass http://joomla_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
        proxy_read_timeout 10s;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Mensaje por defecto en la raiz
        return 200 "Servidor Local de Failover. Accede a /wordpress o /joomla\n";
        add_header Content-Type text/plain;
    }
}
