upstream wordpress_backend {
    server wordpress-1:80;
    server wordpress-2:80 backup; # Simula el IP virtual / Keepalived
}

upstream joomla_backend {
    server joomla-1:80;
    server joomla-2:80 backup;
}

server {
    listen 80;
    server_name localhost;

    # Rutas para WordPress
    location /wordpress/ {
        proxy_pass http://wordpress_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rutas para Joomla
    location /joomla/ {
        proxy_pass http://joomla_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Mensaje por defecto en la raiz
        return 200 "Servidor Local de Failover. Accede a /wordpress o /joomla\n";
        add_header Content-Type text/plain;
    }
}
